# Generated by Django 2.2 on 2019-11-11 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('payment_terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_term', to='payment_terms.PaymentTerm')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='plans.Plan')),
            ],
            options={
                'unique_together': {('plan', 'payment_term')},
            },
        ),
    ]
